### ISSUE TITLE
externalUrl of dynmap (274) is slightly incorrect

### ISSUE THREAD

**Issue by itzg** [SpiGetOrg/SpigetFetcher#11]
When retrieving the dynmap resource info using
```
curl --request GET \
  --url https://api.spiget.org/v2/resources/274
```

it responds with 
```
{
	"external": true,
	"file": {
		"type": "external",
		"size": 0,
		"sizeUnit": "",
		"url": "resources/dynmap%C2%AE.274/download?version=443469",
		"externalUrl": "https://dev.bukkit.org/projects/dynmap/files/3670362"
	},
.
.
.
```

however, the correct download URL for that resource is `https://dev.bukkit.org/projects/dynmap/files/3670362/download`.

First reported in https://github.com/itzg/docker-minecraft-server/issues/1378

**Comment by InventivetalentDev** [comment]
the download button on spigotmc does go to `https://dev.bukkit.org/projects/dynmap/files/3670362`, can't really do much about that :/

**Comment by itzg** [comment]
Totally understand. Thanks for the follow up.
